package com.immatricious.macromanager.event;

public enum MMEventType {
	//Task Events
	TASK_FETCHED,//
	TASK_SENT,
	TASK_INSERT,//
	TASK_REMOVE,//
	TASK_POOLED,//
	TASK_UNPOOLED,//
	TASK_ASSIGNED,//
	
	CHARACTER_ADDED,//
	CHARACTER_REMOVED,
	CHARACTER_UPDATED,//
	CHARACTER_LOGGED_ON,//
	CHARACTER_LOGGED_OFF,//
	CHARACTER_NEXT_TASK,//
	
	ACCOUNT_ADDED,//
	ACCOUNT_REMOVED,
	ACCOUNT_UPDATED,
	ACCOUNT_LOGGED_ON,//
	ACCOUNT_LOGGED_OFF,//
	
	PATH_ADDED,//
	PATH_REMOVED,//
	PATH_UPDATED,//
	
	ZONE_ADDED,
	ZONE_REMOVED,
	ZONE_UPDATED,
	
	HASHLOC_ADDED,
	HASHLOC_REMOVED,
	HASHLOC_UPDATED,
	
	CONNECTION_LOGGED_ON,//
	CONNECTION_LOGGED_OFF,//
	CONNECTION_STARTED,//
	CONNECTION_ENDED,//
	
	MAP_LOADED,//
	
	RCV_FETCH,//
	RCV_LOCATE,//
	RCV_CHAT,//
	RCV_UPDATE_BUDDIES,//
	RCV_UPDATE_CHAR,//
	RCV_MAPDATA,//
	
	SENT_MSG,
	
	LOADED_APP_INPUT,
	LOADED_APP_ERROR,
	
	CMD_STRING;
}
